CREATE TABLE PERSON
(

	ID NUMBER(11) NOT NULL PRIMARY KEY,
	NAME VARCHAR2(50) NOT NULL,
	EMAIL VARCHAR2(50) NOT NULL,
	JOB_TITLE VARCHAR2(50) NOT NULL,
	PHONE_NUMBER VARCHAR2(50) NOT NULL,
	CREATION_DATE VARCHAR2(100) NOT NULL,
	ACTIVE NUMBER(100) NOT NULL,
);